apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vr5ko37fr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e86efcd900feb3c0e9cf6fdd7dc673ce4a720a42@sha256:71a6743f5ff15101337c67d5f413bd411f0f2a3eb5fb8ca7a08900ff8307d133
          name: container-image
